### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Max0menia** [lxndrblz/forensicsim#5]
Hi there,

I receive the following error
ms_teams_parser.exe -f "f:\IndexedDB\https_teams.microsoft.com_0.indexeddb.leveldb" -o c:\temp\levelDB\level.json

Could not decode reply chain

thanks

**Comment by lxndrblz** [comment]
Hi there,

Thanks for filling an issue.

This error should only occur if the underlying Python library that I am using could not decode the particular object store.


Would you be able to provide me with a sanitized copy of the file? I could then do some more digging and hopefully add a better error handling.


It is worth mentioning that the error occurs per individual message, so if you get the error, you should still be able to see the remaining message.

Going forward, i will implement a more detailed error message that returns the flawed record at least in a binary format.

**Comment by Max0menia** [comment]
Dear Alexander,

First of all, thank you and the open-source community for the work you guys are doing to help us.

Unfortunately, I cannot provide you a copy due to confidentiality reasons. However, if you have any idea how I can support you with debugging the issue, more than happy to help. Please see below the message is receive

***@***.***

Best,
Steve

**Comment by lxndrblz** [comment]
@Max0menia Thanks for the swift response and your kind words.

I will try to reproduce the error message using one of my own Teams instances and try to make the error message more descriptive.

**Comment by Max0menia** [comment]
Thanks Alex, let me know when done so I can try on my side, best
Steve

**Comment by lxndrblz** [comment]
@Max0menia Hi there, I've just pushed an updated version that is much more descriptive.

Would you mind testing the new version on your data?

**Comment by Max0menia** [comment]
Hi Alex, I still receive an error

“Could not decode the following item in the reply chain (output is not deduplicated).”

I can send you the entire error if you let me know your email address.

Best
steve

**Comment by lxndrblz** [comment]
@Max0menia Thanks for the feedback.

My personal email is mail {at} alexbilz {dot} com.

**Comment by malamirada** [comment]
Hello, I am also interested in the solution of this error, because I am receiving the same error message as @Max0menia.
Thank you very much anyway for your wonderful work, Alex.

**Comment by lxndrblz** [comment]
@malamirada  I was able to reproduce this error myself. Unfortunately, I haven't gotten around to resolving this issue but I am hopeful I'll be able to provide a solution in the upcoming days.

**Comment by lxndrblz** [comment]
Just wanted to report back that the error seems to be caused by bytes that could not be decoded by UTF-8. In my case these were for the German Letters Ü (0xfc) and Ö (0xf6). Still investigating a generalized solution for this problem.

**Comment by lxndrblz** [comment]
@Max0menia and @malamirada Would you two mind checking if the script included in the fix_unicode_decode branch resolved the errors you were seeing?

**Comment by malamirada** [comment]
Hi Alex, sorry but I'dont understand. I'm only use the exe from the release, not the source code, so I have to wait until the release with the fix will be published. Do you want that I test something before publish the release?

**Comment by lxndrblz** [comment]
@malamirada Thanks for your response. I've just built a new release using Travis. Feel free to test the new release (v0.5.0) and let me know, if you are still getting any errors.

**Comment by malamirada** [comment]
Tested!! It's work like a charm!! The Ldb file has been processed until the end.

No errors raised, only this messages:
"bs4\__init__.py:332: MarkupResemblesLocatorWarning: "\\anyserver\anypath\anyfileordirectory" looks like a filename, not markup. You should probably open this file and pass the filehandle into Beautiful Soup."

Which is a file actually referenced on the teams conversation.

Thank you very much for the fix!!

**Comment by lxndrblz** [comment]
@malamirada Nice! - Thanks for your feedback.

The error you got is thrown by Beautiful Soup. I need to check if it could be suppressed.
